# Generated by Django 3.1.1 on 2020-09-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='plz',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
