# Generated by Django 3.1.1 on 2020-09-09 07:00

from django.db import migrations, models
import map.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('details', models.ImageField(max_length=255, upload_to='')),
                ('image', models.ImageField(upload_to='cars')),
                ('location', models.ForeignKey(on_delete=map.models.Map, to='map.map')),
            ],
        ),
    ]
