# Generated by Django 3.1.1 on 2020-09-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='ps',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cars',
            name='details',
            field=models.CharField(max_length=255),
        ),
    ]
