# Generated by Django 3.1.1 on 2020-09-23 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_cartypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='cartypes',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='cars.cartypes'),
            preserve_default=False,
        ),
    ]
