# Generated by Django 3.1.1 on 2020-09-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_cars_cartypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartypes',
            name='types',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
